version: '3.1'
services:
  proxy:
    volumes:
     - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf:ro
    command: [nginx-debug, '-g', 'daemon off;']
  app:
    build:
      dockerfile: dockerfile.dev 
    ports:
     - '3000:3000'
     - '3002:3002'