version: '3.1'
services:
  proxy:
    container_name: proxy
    image: nginx:1.21.4
    volumes:
     - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
     - '80:80'
     - '443:443'
    networks:
     - internal
  app:
    container_name: app
    build:
      context: .
      dockerfile: dockerfile
    networks:
     - internal

networks:
  internal:
