export default {
  names: {
    refundPrice: '환불 예정 금액',
    bankName: '은행명',
    bankAccountNum: '계좌번호',
    accountHolder: '예금주',
    refundReason: '환불 사유'
  },
  rules: {
    required: '{_field_} 항목을 반드시 입력해 주세요.',
    requiredFocus: '{_field_} 항목을 반드시 입력해 주세요.',
    requiredNoname: '입력되지 않은 필수 사항이 존재합니다.',
    requiredSelect: '{_field_} 항목을 반드시 선택해 주세요.',
    selectedImage: '{_field_} 을(를) 반드시 업로드 해주세요',
    uploadImage: '{_field_} 항목을 업로드 해주세요',
    includeAlphabet: '{_field_}에는 한개이상의 영문자가 포함되어야 합니다.',
    includeNumber: '{_field_}에는 한개이상의 숫자가 포함되어야 합니다.',
    includeSpecial: '{_field_}에는 한개이상의 특수문자가 포함되어야 합니다.',
    alphaDash: '{_field_}에는 영어 알파벳 대소문자, 숫자, 언더바(_), 하이픈(-)만 포함 가능합니다.',
    alphaNum: '{_field_} 항목은 영어 알파벳과 숫자만 포함 가능합니다.',
    byteLength: '{_field_}은(는) {min}바이트 이상 {max}바이트 이하로 입력해주세요.',
    charLength: '{_field_}은(는) {min}바이트 이상 {max}바이트 이하로 입력해주세요.',
    charLengthMin: '{_field_}은(는) {min}바이트 이상으로 입력해주세요.',
    charLengthMax: '{_field_}은(는) {max}바이트 이하로 입력해주세요.',
    correctLength: '{_field_}은(는) 꼭 {length}자 이어야 합니다..',
    length: '{_field_}은(는) {min}자 이상 {max}자 이하로 입력해주세요.',
    lengthMin: '{_field_}은(는) {min}자 이상으로 입력해주세요.',
    lengthMax: '{_field_}은(는) {max}자 이하로 입력해주세요.',
    imageMinLength: '{_field_}은(는) 최소 {min}개 이상 이미지를 등록해주세요.',
    confirm: '{_field_}이(가) 일치하지 않습니다.',
    password: '비밀번호는 영문자, 숫자, 특수문자만 입력가능합니다.',
    accountLocked: '비밀번호 반복 오류로 60초동안 계정이 잠겼어요.',
    email: '이메일 형식이 올바르지 않습니다.',
    emailRegistered: '이미 가입된 이메일입니다.',
    nickname: '닉네임은 영문자, 숫자, 언더바(_)만 입력가능합니다.',
    nicknameRegistered: '이미 존재하는 닉네임 입니다.',
    isPhoneNumber: '연락처 항목을 형식에 맞게 입력해 주세요.',
    summonerName: '영문, 한글 또는 0~9의 숫자 및 공백만 사용해야 합니다',
    hanaCoupon: '{_field_}은(는) 반드시 Q + 7자리 숫자 또는 알파벳 대문자로 입력해야 합니다',
    hanaCouponTeam: '{_field_}은(는) 반드시 T + 7자리 숫자 또는 알파벳 대문자로 입력해야 합니다.',
    kartRider: '한글 2-6자, 영어 4-12자로 입력해야 하며 특수문자 사용은 불가합니다.',
    kartRiderUid: '영문+숫자로 13자리를 입력해주세요.',
    byEmail: '{_field_}은(는) 이메일 형식으로 입력해야합니다.',
    randomToYou: '숫자+영문대문자로 7자리를 입력해주세요.',
    teamName: '영문, 숫자, 띄어쓰기, 언더바(_), 빼기(-), 마침표(.), 따옴표(\') 만 허용됩니다.',
    teamNameVacated: '이미 사용하고 있는 팀 이름입니다.',
    channelTitleUsed: '다른 채널에서 사용중 입니다.',
    timeRequired: '{_field_} 항목을 반드시 입력해 주세요.',
    extraRequired: '{_field_} 항목을 삭제 하거나 입력해주세요.',
    sixPassword: '{_field_} 항목은 6개의 숫자를 입력해주세요.',
    minMax: '{_field_} 항목은 {min}이상 {max}이하 여야 합니다.',
    url: '링크 규칙에 맞춰 입력해주세요.(http:// 또는 https:// 로 시작함.)',
    file: '{_field_}은(는) 파일을 한 개 이상 등록 하셔야 합니다.',
    notEqual: '같은 {_field_}은(는) 등록 할 수 없습니다.'
  }
}
